---
roles:
  - name: geerlingguy.varnish
    version: 3.3.0
  - src: "https://github.com/damianlewis/ansible-role-mysql.git"
    name: damianlewis.mysql
  - name: geerlingguy.php-versions
    version: 5.0.0
  - name: geerlingguy.php
    version: 4.7.0
  - name: geerlingguy.composer
    version: 1.9.0
  - name: elastic.elasticsearch
    version: 'v7.15.1'

collections:
  - name: community.general
    version: 3.7.0
  - name: ansible.posix
    version: 1.3.0
  - name: geerlingguy.php_roles
    version: 1.0.0
  - name: nginxinc.nginx_core
    version: 0.3.0
